apiVersion: v2
name: helm-chart
version: 4.0.0

maintainers:
  - name: Matthew Lau
    email: lau.cy.matthew@gmail.com

keywords:
  - aws
  - kubernetes

description: A simple Python application running on EKS
