name: Destroy AWS infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_APP_WORKDIR: ./terraform/app

jobs:
  terraform-destroy:
    name: "Terraform destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_APP_WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: us-east-1
      - name: Set-up SSH public key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PUBLIC_KEY" > ~/.ssh/aws_app.pub
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/aws_app
        env:
          SSH_PUBLIC_KEY: ${{secrets.SSH_PUBLIC_KEY}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
