name: Destroy AWS infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  TF_APP_WORKDIR: ./terraform/app

jobs:
  terraform-destroy:
    name: "Terraform destroy"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_APP_WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE_ARN }}
          aws-region: us-east-1
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve
